// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDfPn_OyosMM8-vPeSgSzK2Ms4Y0Ez4dM',
    appId: '1:962529220510:web:bebb9bbf5d6ea8c14ea88f',
    messagingSenderId: '962529220510',
    projectId: 'valenx-1004',
    authDomain: 'valenx-1004.firebaseapp.com',
    storageBucket: 'valenx-1004.firebasestorage.app',
    measurementId: 'G-XG3X8ZEFV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9iNz1-yYiQmpoQ6VJ2KJfORRju--gAHE',
    appId: '1:962529220510:android:1d29d19a65554c634ea88f',
    messagingSenderId: '962529220510',
    projectId: 'valenx-1004',
    storageBucket: 'valenx-1004.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC8pvfTHUnrYlf5b512hmGl25_nPcB1u4',
    appId: '1:962529220510:ios:d697d6e19a3453354ea88f',
    messagingSenderId: '962529220510',
    projectId: 'valenx-1004',
    storageBucket: 'valenx-1004.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
